# Generated by Django 3.0.8 on 2020-08-27 03:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_healthdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='fat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='muscle_mass',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
