# Generated by Django 3.0.8 on 2020-08-27 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200827_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_id',
        ),
    ]
