# Generated by Django 3.0.8 on 2020-08-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_person_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
