# Generated by Django 3.0.8 on 2020-08-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200827_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(default=999, max_length=20),
            preserve_default=False,
        ),
    ]
