# Generated by Django 3.0.8 on 2020-09-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
