# Generated by Django 3.1.5 on 2021-02-01 10:15

import django.core.validators
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_author_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, '5文字以上です！'), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', '英数字のみです！')])),
                ('age', models.IntegerField(default=0, validators=[store.models.check_age])),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='HealthData',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
