# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT StoreHealthData.wsgi

beta_settings:
    cloud_sql_instances: 'balmy-platform-305710:asia-northeast1:test'

runtime_config:
  python_version: 3
# [END runtime]
